## Application config
app:
  property:
    env: PROD

## Spring config
spring:
  datasource:
    jdbc-url: jdbc:mysql://192.168.2.225:3306/licenses?useUnicode=true&characterEncoding=utf-8&useSSL=false